### ISSUE TITLE
node_modules

### ISSUE THREAD

**Issue by rajibulanam** [weykon/react-native-png#1]
After Adding this Package getting this error.
error: Error: Unable to resolve module stream from F:\test\test_folder\node_modules\react-native-png\src\png.js: stream 
could not be found within the project or in these directories:
  node_modules
  2 |
  3 | let util = require("util");
> 4 | let Stream = require("stream");
    |                       ^
  5 | let Parser = require("./parser-async");
  6 | let Packer = require("./packer-async");
  7 | let PNGSync = require("./png-sync");

my package.json file
{
  "name": "test_folder",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-png": "^0.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by weykon** [comment]
@rajibulanam 
Hi!, have a try this
```sh
npm install stream
```
😁

**Comment by weykon** [comment]
> @rajibulanam Hi!, have a try this
> 
> ```shell
> npm install stream
> ```
> 
> 😁

I'm using stream 0.0.2 version by Julian Gruber is ok. 
more info, here is [git repository](https://github.com/juliangruber/stream)

**Comment by rajibulanam** [comment]
Dear,
Brother I am trying to use your code in react-native CLI. But facing an error. 
Please give an example of this code, can read from FS. This code is from your test folder.

import { PNG } from '../src/png';


// load file from fs read. 
import * as fs from 'fs';
const buffer_from_fs = fs.readFileSync('./test/1.png');
const png = PNG.sync.read(buffer_from_fs,);
console.log('png ', png)

**Comment by weykon** [comment]
I'm so sorry for there is not explicit why will appear "fs" module.
React Native is not NodeJS environment so we can not use "fs" module.

--- 

how to do with loading png in React Native? 
We use Image from react-native.  [read here](https://reactnative.dev/docs/image)
```ts
import {Image} from "react-native"
// if your png is static png
// or some dynamic import ? 
```
[React Native Image Component Code](https://snack.expo.dev/)

And what is kind of png  source you loaded ? 
I don't know the specify circumstance.

however, thank you for put this issue, that realize me to add more information.
I admit it's still very imperfect, I was apologetic took your time... 😢

**Comment by rajibulanam** [comment]
Hi, Brother I am using this way at react-native. I am getting error in when I am trying to ad your PNG library in my code. Please guide me how I can use your library on my project.

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React, {useState, useEffect} from 'react';
import type {Node} from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
  Image,
} from 'react-native';

import {
  Colors,
  DebugInstructions,
  Header,
  LearnMoreLinks,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';
import { PNG } from 'react-native-png';


import ImgToBase64 from 'react-native-image-base64';

/* $FlowFixMe[missing-local-annot] The type annotation(s) required by Flow's
 * LTI update could not be added via codemod */
const Section = ({children, title}): Node => {
  const isDarkMode = useColorScheme() === 'dark';
  return (
    <View style={styles.sectionContainer}>
      <Text
        style={[
          styles.sectionTitle,
          {
            color: isDarkMode ? Colors.white : Colors.black,
          },
        ]}>
        {title}
      </Text>
      <Text
        style={[
          styles.sectionDescription,
          {
            color: isDarkMode ? Colors.light : Colors.dark,
          },
        ]}>
        {children}
      </Text>
    </View>
  );
};

const App: () => Node = () => {
  const [content, setContent] = useState(null);
  const isDarkMode = useColorScheme() === 'dark';
   const foo = require('./assets/test.png');
   const fooURI = Image.resolveAssetSource(foo).uri;
  
  ImgToBase64.getBase64String(fooURI)
  .then(base64String => 
    setContent(base64String)
    )
  .catch(err => console.log(err));
 console.log('Base64: ' + content);
const png0 = PNG.sync.read(content);
console.log('png ', png0);

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar
        barStyle={isDarkMode ? 'light-content' : 'dark-content'}
        backgroundColor={backgroundStyle.backgroundColor}
      />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        <Header />
        <View
          style={{
            backgroundColor: isDarkMode ? Colors.black : Colors.white,
          }}>
          <Section title="Step One">
          <Text>TestAssetsApp</Text>

          </Section>
          <Section title="See Your Changes">
            <ReloadInstructions />
          </Section>
          <Section title="Debug">
            <DebugInstructions />
          </Section>
          <Section title="Learn More">
            Read the docs to discover what to do next:
          </Section>
          <LearnMoreLinks />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
  },
  highlight: {
    fontWeight: '700',
  },
});

export default App;

**Comment by weykon** [comment]
thank you again !

what error crash info? 

I am not really sure whether "content" could be get correctly because of your code at "setContent" is async operation.

if console.log do not output the "content" you need deal with this async problem, make sure it ordering right.

and try ImgToBase64.getBase64String('file://youfileurl') , it seem like no need for using require('./assets/test.png');

try this code 
```ts
ImgToBase64.getBase64String('./assets/test.png')
.then(base64String =>
     setContent(base64String);
     console.log('Base64: ' + base64String);
     const png0 = PNG.sync.read(base64String);
     console.log('png ', png0);
)
.catch(err => console.log(err));

```

**Comment by rajibulanam** [comment]
Dear Brother,
**These are my code:**
```
   const foo = require('./assets/test.png');
   const fooURI = Image.resolveAssetSource(foo).uri;
  
  ImgToBase64.getBase64String(fooURI)
  .then(base64String => 
    console.log('png ', PNG.sync.read(base64String))
    )
  .catch(err => console.log(err));
```

**The error I am getting:**
```
 LOG  Running "test_folder" with {"rootTag":1}
 LOG  [Error: unrecognised content at end of stream] 
```

I am very much interested to use your library, this is the reason I am posting it day by day. 
Thanks

**Comment by weykon** [comment]
what block throw this error ?

**Comment by rajibulanam** [comment]
This part of the Code throw error:
`console.log('png ', PNG.sync.read(base64String))`

**Comment by weykon** [comment]
let's check the base64String , [online generate png](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjPwaLsvfn7AhUZ0GEKHVNRCDkQFnoECA8QAQ&url=https%3A%2F%2Fonlinepngtools.com%2Fconvert-base64-to-png&usg=AOvVaw28qmiLau4bq4-mkunrwsxY)

if it is no problem, that something wrong at dependencies packages in this module...

I need to fix this module on supplementing complete-environment

**Comment by weykon** [comment]
try this to your project https://github.com/browserify/browserify

**Comment by weykon** [comment]
the important, it is base64String into a Buffer Object, 

that I was careless set the type is any, it must be Buffer

**Comment by weykon** [comment]
if you appear 
```
[ReferenceError: Can't find variable: Buffer]
```

to set the Buffer can be referenced.
```ts
global.Buffer = global.Buffer || require('buffer').Buffer
```

**Comment by weykon** [comment]
![image](https://user-images.githubusercontent.com/36456814/207668269-c2481670-e79c-4d72-800a-624ad852d237.png)
I copied your code and run it completely !

**Comment by weykon** [comment]
> I am very much interested to use your library, this is the reason I am posting it day by day.

Thank you so much, I am honored to be appreciated by you !

**Comment by weykon** [comment]
take a new v0.0.5 version, It might be better
```sh
yarn add "react-native-png"
```
```sh
npm update "react-native-png"
```

**Comment by rajibulanam** [comment]
Brother,
Thanks.

**Comment by weykon** [comment]
Thank you for your participation
